### PR TITLE
remove duplicate code from integration tests

### PR DESCRIPTION
**Pull request by lbventura**
I am seeing some test flakiness which disappears once I repeat the failing tests with `pytest tests/test_integration.py --lf`. This suggests that there might be a problem with the random seed, although it is not obvious to me where since some of the other tests pass consistently.

### CODE REVIEW

**Comment by FelixWick** [comment]
I saw this for plotting tests, but not for the integration tests. Anyway, I think that's a good refactoring. Please adjust the expected test results, then I'm fine with merging.

**Comment by lbventura** [comment]
> I saw this for plotting tests, but not for the integration tests. Anyway, I think that's a good refactoring. Please adjust the expected test results, then I'm fine with merging.

The thing is, I was expecting no change in the results at all. If these have changed, it is likely because the np.seed is not the same everywhere, I think.
Nevertheless, I will try your suggestion and check if, after changing to these new values, if the tests pass consistently by running them several times.

**Comment by FelixWick** [comment]
It is expected that the results changed compared to main, because I had reset the seed for each test, while you set it once globally.
So, you might just try to reset it in each test.

**Comment by lbventura** [comment]
The tests now pass. The confusing issue before was that repeating the failing tests caused them to pass, but this could be due to some caching happening on `pytest` side once the `--lf` option is used.

**Review by FelixWick — APPROVED** [review]

**Pull request merged**
